---
- name: Install nginx repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: name=nginx state=present

- name: Change default config of nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  tags: nginx-config
  notify: restart nginx

- name: Copy nginx configuration for laravel
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Start on boot
  service:
    name: nginx
    enabled: yes
